### ISSUE TITLE
Help with ReactorFaceSwap MaskingHelper

### ISSUE THREAD

**Issue by Tywors** [bruefire/ComfyUI-SeqImageLoader#4]
You could add an example with FaceSwap's Masking Helper Reaction, I can't get it to work. Thank you!

**Comment by bruefire** [comment]
I'm not familiar with FaceSwap and also I can't say I fully understand about your intent, but by creating the following workflow, you can input a manual mask into the masking helper:
https://imgur.com/a/YzgjFUH

It may be unclear, but in the example above, only the left half of the face was swapped through the masking helper using manual masks.
I added this workflow to the sample_workflows directory as a sample.
